
package com.askbri.metier;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://metier.AskBri.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertEuroToDh")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertEuroToDh", targetNamespace = "http://metier.AskBri.com/", className = "com.askbri.metier.ConvertEuroToDh")
    @ResponseWrapper(localName = "ConvertEuroToDhResponse", targetNamespace = "http://metier.AskBri.com/", className = "com.askbri.metier.ConvertEuroToDhResponse")
    @Action(input = "http://metier.AskBri.com/BanqueWS/ConvertEuroToDhRequest", output = "http://metier.AskBri.com/BanqueWS/ConvertEuroToDhResponse")
    public double convertEuroToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<com.askbri.metier.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAccounts", targetNamespace = "http://metier.AskBri.com/", className = "com.askbri.metier.GetAllAccounts")
    @ResponseWrapper(localName = "getAllAccountsResponse", targetNamespace = "http://metier.AskBri.com/", className = "com.askbri.metier.GetAllAccountsResponse")
    @Action(input = "http://metier.AskBri.com/BanqueWS/getAllAccountsRequest", output = "http://metier.AskBri.com/BanqueWS/getAllAccountsResponse")
    public List<Account> getAllAccounts();

    /**
     * 
     * @param code
     * @return
     *     returns com.askbri.metier.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://metier.AskBri.com/", className = "com.askbri.metier.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://metier.AskBri.com/", className = "com.askbri.metier.GetAccountResponse")
    @Action(input = "http://metier.AskBri.com/BanqueWS/getAccountRequest", output = "http://metier.AskBri.com/BanqueWS/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @param solde
     * @param fullName
     * @param code
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AddAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AddAccount", targetNamespace = "http://metier.AskBri.com/", className = "com.askbri.metier.AddAccount")
    @ResponseWrapper(localName = "AddAccountResponse", targetNamespace = "http://metier.AskBri.com/", className = "com.askbri.metier.AddAccountResponse")
    @Action(input = "http://metier.AskBri.com/BanqueWS/AddAccountRequest", output = "http://metier.AskBri.com/BanqueWS/AddAccountResponse")
    public boolean addAccount(
        @WebParam(name = "code", targetNamespace = "")
        Long code,
        @WebParam(name = "fullName", targetNamespace = "")
        String fullName,
        @WebParam(name = "solde", targetNamespace = "")
        double solde);

}
