
package com.askbri.metier;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BanqueImplService", targetNamespace = "http://metier.AskBri.com/", wsdlLocation = "http://localhost:8585/BanqueWS?wsdl")
public class BanqueImplService
    extends Service
{

    private final static URL BANQUEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANQUEIMPLSERVICE_EXCEPTION;
    private final static QName BANQUEIMPLSERVICE_QNAME = new QName("http://metier.AskBri.com/", "BanqueImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8585/BanqueWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANQUEIMPLSERVICE_WSDL_LOCATION = url;
        BANQUEIMPLSERVICE_EXCEPTION = e;
    }

    public BanqueImplService() {
        super(__getWsdlLocation(), BANQUEIMPLSERVICE_QNAME);
    }

    public BanqueImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANQUEIMPLSERVICE_QNAME, features);
    }

    public BanqueImplService(URL wsdlLocation) {
        super(wsdlLocation, BANQUEIMPLSERVICE_QNAME);
    }

    public BanqueImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANQUEIMPLSERVICE_QNAME, features);
    }

    public BanqueImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanqueImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueWS
     */
    @WebEndpoint(name = "BanqueWSPort")
    public BanqueWS getBanqueWSPort() {
        return super.getPort(new QName("http://metier.AskBri.com/", "BanqueWSPort"), BanqueWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueWS
     */
    @WebEndpoint(name = "BanqueWSPort")
    public BanqueWS getBanqueWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://metier.AskBri.com/", "BanqueWSPort"), BanqueWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANQUEIMPLSERVICE_EXCEPTION!= null) {
            throw BANQUEIMPLSERVICE_EXCEPTION;
        }
        return BANQUEIMPLSERVICE_WSDL_LOCATION;
    }

}
